on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  dm_metric_test:
    runs-on: ubuntu-latest
    name: Run deploy metric test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start DM
        id: start_dm
        uses: ./ 
        with:
          status: 'created'

      - name: Update DM
        id: update_dm
        uses: ./ 
        with:
          verbose: 'true'
          dm_token: ${{ secrets.LOCAL_EXTENSIONS_DM_PROD_TOKEN }}
          server: ${{ secrets.LOCAL_EXTENSIONS_DM_SERVER }}
          createdAt: ${{ steps.start_dm.outputs.createdAt }}
          name: 'dm-gha'
          version: 'master'
          repositoryUrl: 'https://github/mammutmw/dm-gha'
          commitSha: '${{github.sha}}'
          environment: 'development'
          status: 'success'
          productName: 'dm-gha'
          capabilityName: 'CMP'

      - name: Get output
        run: echo "${{ steps.update.outputs.location }}"