on:
  push:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  dm_tetric_test:
    runs-on: ubuntu-latest
    name: Run deploy metric test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        id: test
        with:
          verbose: 'true'
      - name: Get output
        run: echo "${{ steps.test.outputs.location }}"